# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 18, 28, 46, 342062)),
        ),
    ]
